# Generated by Django 4.0.6 on 2022-07-19 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='TCU Students Only', regex='g([0-9]{2})([0-9]{2})([0-9]{3})@tcu\\.ac\\.jp')], verbose_name='email address'),
        ),
    ]
