# Generated by Django 4.0.6 on 2022-07-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cafeteria_ticket',
            field=models.IntegerField(default=5, verbose_name='cafeteria ticket'),
        ),
    ]
