# Generated by Django 4.0.6 on 2022-07-24 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 15, 3, 8, 759395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seat',
            name='half',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')]),
        ),
    ]
