# Generated by Django 4.0.6 on 2022-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_alter_seat_seat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.IntegerField(blank=True, default=999),
        ),
    ]
