# Generated by Django 4.0.6 on 2022-07-24 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafeteria', '0006_alter_seat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_id',
        ),
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
