# Generated by Django 4.0.6 on 2022-07-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_genre_alter_thread_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('genre_id',)},
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
