# Generated by Django 4.0.6 on 2022-07-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_genre_options_alter_genre_genre_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_posted',)},
        ),
    ]
