# Generated by Django 4.0.6 on 2022-07-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_thread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('last_update',)},
        ),
    ]
